### ISSUE TITLE
Menu bar doesn't show

### ISSUE THREAD

**Issue by somelinguist** [michelolvera/vs-ghostwriter#7] opened 2019-06-06 20:40 UTC
The menu bar doesn't show in windowed mode. I can access the menu by clicking where it should be or using keyboard shortcuts.

In full-screen mode, I have the opposite problem: the menu bar shows, but clicking on it or using keyboard shortcuts does not reveal the menus.

Using ghostwriter 1.8.0 from this repo.

**Comment by michelolvera** [comment] 2019-06-09 15:55
Screenshots and details of the OS that you use please. Greetings.

**Comment by somelinguist** [comment] 2019-06-10 16:36
Here are the screenshots.

I'm using Windows 10 Pro, version 1903.

Thanks!

Windowed with menu closed (menu bar doesn't display):
![windowed_menu_closed](https://user-images.githubusercontent.com/3488298/59210494-5419fd00-8b73-11e9-8adc-597f73b35673.jpg)

Windowed with menu opened via ALT + f or click (menu bar doesn't display)
![windowed_menu_open](https://user-images.githubusercontent.com/3488298/59210528-68f69080-8b73-11e9-89e0-4bb5bbad6198.jpg)

Full screen (menu bar displays, but menus will not open)
![full_screen](https://user-images.githubusercontent.com/3488298/59210552-790e7000-8b73-11e9-9514-a88ce25365aa.jpg)

**Comment by michelolvera** [comment] 2019-07-03 18:04
I have not received any more reports and I have not managed to replicate them on my computer. Is not it because of the custom theme that you use?

**Comment by somelinguist** [comment] 2019-07-03 18:30
It's set to use the built-in Classic Light theme, and only built-in themes are installed. Any other possibilities? Thanks.

**Comment by Timecrash** [comment] 2019-08-23 12:02
I'm having a similar issue. At least on one of my Windows machines, the menu doesn't display when in fullscreen. I can, however, click on the approximate place where an option _should_ be, and it'll execute it as normal. Unlike somelinguist, however, my menu bar works in window mode as intended.

I did notice something strange when trying to take a screenshot, however. The menu appeared to the Print Screen command, but not me. I only saw it displayed when I copied it into Paint. This was full-screen:
![Untitled3](https://user-images.githubusercontent.com/15052506/63591296-58ec2b80-c57c-11e9-9ce9-9a778400ed0c.png)

**Comment by michelolvera** [comment] 2019-10-10 00:07
The installer and Qt version have been updated, could you try this version and tell me what the result was?

**Comment by Timecrash** [comment] 2019-10-10 02:47
I'm afraid this still doesn't work.

**Comment by somelinguist** [comment] 2019-11-25 21:24
This seems to have fixed it for me. Sorry for the late reply.

**Comment by PrSunflower** [comment] 2021-05-15 18:42
Hi just stumbling upon this issue. @somelinguist if the problem is fixed could you close this issue please?

**Closed** 2021-05-22 03:19 UTC
